package com.fjourdren.theatrum.domain.service;

import com.fjourdren.theatrum.application.port.in.PathTemplateUseCase;
import com.fjourdren.theatrum.domain.constant.PathConstants;
import com.fjourdren.theatrum.domain.constant.TemplateConstants;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Supplier;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Resolves path templates: user variables {@code {var}} extracted from URL patterns and
 * builtin functions {@code {%FUNC%}} generated at resolution time.
 */
@Component
public class PathTemplateService implements PathTemplateUseCase {

    /** Only alphanumerics, underscores, hyphens and single dots (no consecutive dots). */
    private static final Pattern ALLOWED_CHARS = Pattern.compile("[a-zA-Z0-9_\\-.]+");

    private static final DateTimeFormatter STARTING_DATE_FORMATTER =
            DateTimeFormatter.ofPattern(TemplateConstants.STARTING_DATE_FORMAT);

    private final Map<String, Supplier<String>> builtinFuncs = new ConcurrentHashMap<>();

    public PathTemplateService() {
        builtinFuncs.put(TemplateConstants.FUNC_NAME_STARTING_DATE,
                () -> LocalDateTime.now().format(STARTING_DATE_FORMATTER));
        builtinFuncs.put(TemplateConstants.FUNC_NAME_UUID, () -> UUID.randomUUID().toString());
    }

    public void registerBuiltinFunc(String name, Supplier<String> fn) {
        builtinFuncs.put(name, fn);
    }

    /**
     * Extracts the {@code {var}} values from {@code input} using {@code template}, plus a
     * {@code FILENAME} entry (basename) when the input is a path.
     *
     * @throws IllegalArgumentException if the input does not match the template
     */
    @Override
    public Map<String, String> extractValues(String template, String input) {
        template = template.replace('\\', '/');
        input = input.replace('\\', '/');

        var varNames = new ArrayList<String>();
        // lookingAt() anchors at the start only: a longer input still matches its template prefix.
        var matcher = Pattern.compile(buildPattern(template, varNames)).matcher(input);
        if (!matcher.lookingAt()) {
            throw new IllegalArgumentException("input does not match template");
        }

        var result = new LinkedHashMap<String, String>();
        for (int i = 0; i < varNames.size(); i++) {
            result.put(varNames.get(i), matcher.group(i + 1));
        }

        if (input.contains("/")) {
            var filename = base(input);
            if (!filename.isEmpty() && !filename.equals(".") && !filename.equals("/")) {
                result.put(TemplateConstants.VAR_NAME_FILENAME, filename);
            }
        }
        return result;
    }

    /** Whether {@code input} matches {@code template} in full (anchored at both ends). */
    @Override
    public boolean matchesTemplate(String template, String input) {
        template = template.replace('\\', '/');
        input = input.replace('\\', '/');

        // matches() anchors both ends.
        return Pattern.compile(buildPattern(template, new ArrayList<>())).matcher(input).matches();
    }

    /**
     * Replaces builtin placeholders {@code {%FUNC%}} then user variables {@code {var}}, and
     * cleans the resulting path.
     * <p>
     * Builtin values are read from {@code vars} (pre-generated by {@link #generateBuiltinVars});
     * a known builtin absent from {@code vars} is left as-is, which stream key computation relies on.
     *
     * @throws IllegalArgumentException on an unknown builtin function or an unsanitizable value
     */
    @Override
    public String replacePlaceholders(String text, Map<String, String> vars) {
        // Phase 1: builtin placeholders {%FUNC%}
        var result = replaceAll(TemplateConstants.FUNC_CALL_REGEX, text, m -> {
            var funcName = m.group(1);
            if (!builtinFuncs.containsKey(funcName)) {
                throw new IllegalArgumentException("unknown builtin function: " + funcName);
            }
            var val = vars.get(funcName);
            return val != null ? sanitizeValue(val) : m.group();
        });

        // Phase 2: user variables {var}
        result = replaceAll(TemplateConstants.ANY_VAR_REGEX, result, m -> {
            var val = vars.get(m.group(1));
            return val != null ? sanitizeValue(val) : m.group();
        });

        return clean(result).replace('\\', '/');
    }

    /**
     * Scans a template for {@code {%FUNC%}} patterns and calls each registered generator once,
     * returning a map of function name to generated value. Unknown functions are ignored.
     */
    @Override
    public Map<String, String> generateBuiltinVars(String template) {
        var result = new LinkedHashMap<String, String>();
        var matcher = TemplateConstants.FUNC_CALL_REGEX.matcher(template);
        while (matcher.find()) {
            var funcName = matcher.group(1);
            var fn = builtinFuncs.get(funcName);
            if (fn != null) {
                result.computeIfAbsent(funcName, k -> fn.get());
            }
        }
        return result;
    }

    String sanitizeValue(String value) {
        if (!ALLOWED_CHARS.matcher(value).matches()) {
            throw new IllegalArgumentException("invalid characters in value: only a-z, A-Z, 0-9, _, - and . are allowed");
        }
        if (value.contains(PathConstants.PARENT_DIR)) {
            throw new IllegalArgumentException("consecutive dots are not allowed");
        }
        return value;
    }

    /** Builds a regex from a template, quoting literals and turning each placeholder into a segment capture. */
    private static String buildPattern(String template, List<String> varNames) {
        var matcher = TemplateConstants.ANY_VAR_REGEX.matcher(template);
        var pattern = new StringBuilder();
        int last = 0;
        while (matcher.find()) {
            pattern.append(Pattern.quote(template.substring(last, matcher.start()))).append(TemplateConstants.VAR_SEGMENT_CAPTURE);
            varNames.add(matcher.group(1));
            last = matcher.end();
        }
        return pattern.append(Pattern.quote(template.substring(last))).toString();
    }

    private static String replaceAll(Pattern pattern, String text, java.util.function.Function<Matcher, String> replacer) {
        var matcher = pattern.matcher(text);
        var out = new StringBuilder();
        while (matcher.find()) {
            matcher.appendReplacement(out, Matcher.quoteReplacement(replacer.apply(matcher)));
        }
        return matcher.appendTail(out).toString();
    }

    /** Port of Go's {@code filepath.Base} for forward-slash paths. */
    private static String base(String path) {
        int end = path.length();
        while (end > 0 && path.charAt(end - 1) == '/') {
            end--;
        }
        if (end == 0) {
            return path.isEmpty() ? "." : "/";
        }
        return path.substring(path.lastIndexOf('/', end - 1) + 1, end);
    }

    /** Port of Go's {@code filepath.Clean} for forward-slash paths. */
    private static String clean(String path) {
        if (path.isEmpty()) {
            return ".";
        }
        var rooted = path.charAt(0) == '/';
        var segments = new ArrayDeque<String>();
        for (var segment : path.split("/", -1)) {
            switch (segment) {
                case "", "." -> {
                }
                case ".." -> {
                    if (!segments.isEmpty() && !"..".equals(segments.peekLast())) {
                        segments.removeLast();
                    } else if (!rooted) {
                        segments.addLast(segment);
                    }
                }
                default -> segments.addLast(segment);
            }
        }
        var joined = String.join("/", segments);
        if (rooted) {
            return "/" + joined;
        }
        return joined.isEmpty() ? "." : joined;
    }
}
